from __future__ import annotations

import re
from pathlib import Path

from wdsync.exceptions import (
    CommandExecutionError,
    ConfigValidationError,
    MissingConfigError,
    NotGitRepositoryError,
    SourceRepositoryError,
)
from wdsync.models import InitResult, ProjectConfig
from wdsync.path_utils import (
    ensure_wsl_environment,
    is_wsl_windows_path,
    normalize_source_path,
    wsl_to_windows_path,
)
from wdsync.runner import CommandRunner

CONFIG_FILENAME = ".wdsync"
_CONFIG_LINE = re.compile(r"^\s*([A-Za-z_]\w*)\s*=\s*(.*)$")


def find_destination_root(runner: CommandRunner, *, cwd: Path | None = None) -> Path:
    try:
        result = runner.run(["git", "rev-parse", "--show-toplevel"], cwd=cwd)
    except CommandExecutionError as exc:
        raise NotGitRepositoryError("wdsync: not inside a git repository") from exc
    return Path(result.stdout_text().strip())


def parse_config_text(text: str) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw_line in text.splitlines():
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        match = _CONFIG_LINE.match(raw_line)
        if match is None:
            continue
        key, value = match.groups()
        if key not in values:
            values[key] = value.strip()
    return values


def _build_project_config(
    *,
    dest_root: Path,
    config_path: Path,
    raw_source: str,
    runner: CommandRunner,
) -> ProjectConfig:
    source_root = normalize_source_path(raw_source)
    if not is_wsl_windows_path(source_root):
        raise ConfigValidationError(
            "wdsync: expected SRC to be a WSL-mounted Windows path like /mnt/c/Users/you/project"
        )
    if not source_root.is_dir():
        raise ConfigValidationError(f"wdsync: SRC path does not exist: {source_root}")

    source_root_windows = wsl_to_windows_path(source_root, runner)
    try:
        runner.run(["git.exe", "-C", source_root_windows, "rev-parse", "--show-toplevel"])
    except CommandExecutionError as exc:
        raise SourceRepositoryError(
            f"wdsync: source path is not a Git repository: {source_root}"
        ) from exc

    return ProjectConfig(
        dest_root=dest_root,
        config_path=config_path,
        source_root=source_root,
        source_root_windows=source_root_windows,
    )


def load_project_config(runner: CommandRunner, *, cwd: Path | None = None) -> ProjectConfig:
    ensure_wsl_environment()
    dest_root = find_destination_root(runner, cwd=cwd)
    config_path = dest_root / CONFIG_FILENAME
    if not config_path.is_file():
        raise MissingConfigError(
            f"wdsync: no {CONFIG_FILENAME} file found at {dest_root}\n"
            "  Create one manually or run: wdsync init /mnt/c/path/to/project"
        )

    raw_values = parse_config_text(config_path.read_text(encoding="utf-8"))
    raw_source = raw_values.get("SRC")
    if raw_source is None or not raw_source.strip():
        raise ConfigValidationError("wdsync: .wdsync is missing a SRC= entry")

    return _build_project_config(
        dest_root=dest_root,
        config_path=config_path,
        raw_source=raw_source,
        runner=runner,
    )


def _git_exclude_path(dest_root: Path, runner: CommandRunner) -> Path:
    result = runner.run(["git", "-C", str(dest_root), "rev-parse", "--git-path", "info/exclude"])
    return Path(result.stdout_text().strip())


def _ensure_exclude_contains(exclude_path: Path, pattern: str) -> bool:
    exclude_path.parent.mkdir(parents=True, exist_ok=True)
    existing = exclude_path.read_text(encoding="utf-8") if exclude_path.exists() else ""
    lines = [line.strip() for line in existing.splitlines()]
    if pattern in lines:
        return False

    prefix = "" if not existing or existing.endswith("\n") else "\n"
    exclude_path.write_text(f"{existing}{prefix}{pattern}\n", encoding="utf-8")
    return True


def init_project(
    source: str,
    runner: CommandRunner,
    *,
    cwd: Path | None = None,
) -> InitResult:
    ensure_wsl_environment()
    dest_root = find_destination_root(runner, cwd=cwd)
    config_path = dest_root / CONFIG_FILENAME
    config = _build_project_config(
        dest_root=dest_root,
        config_path=config_path,
        raw_source=source,
        runner=runner,
    )

    desired_content = "\n".join(
        [
            "# Windows source repo mirrored into this WSL repo",
            "# Generated by wdsync init",
            f"SRC={config.source_root}",
            "",
        ]
    )
    existing = config_path.read_text(encoding="utf-8") if config_path.exists() else None
    wrote_config = existing != desired_content
    if wrote_config:
        config_path.write_text(desired_content, encoding="utf-8")

    exclude_path = _git_exclude_path(dest_root, runner)
    updated_exclude = _ensure_exclude_contains(exclude_path, CONFIG_FILENAME)
    return InitResult(
        config=config,
        wrote_config=wrote_config,
        exclude_path=exclude_path,
        updated_exclude=updated_exclude,
    )
